name: SLSA Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build packages
        run: yarn build
        
      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator@v1.6.0
        with:
          base64-subjects: true
          upload-assets: true 